backend:
  name: github
  repo: ompatell28/STEREOSCOPIA_
  branch: main
  api_root: https://api.github.com

media_folder: "images"
public_folder: "/images"

collections:
  - name: "portfolio"
    label: "Portfolio Gallery"
    folder: "data/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Project Title", name: "title", widget: "string", default: "CINEMATIC CAPTURE" }
      - { label: "Project Image", name: "image", widget: "image" }
      - { label: "Cyber Tag", name: "tag", widget: "string", default: "VISUAL MATRIX" }